#Python Ideas
print("AITA")
print("Binary Writer")
print('Substitute teacher Checker')
print('language converter')
print('Scrabble game')
print('Statics Solver')
print('Statistics functions')
print('HillcrestJamestown App')
print('Path finding visualizer algorythym')
print('Space wars game with GUI to beat it')
print('Rubiks cube solver')
print('Automated code uploader (Github/ IPad')